### ISSUE TITLE
Upgrade @mui/material from 5.4.4 to 5.8.2 dependency

### ISSUE THREAD

**Issue by itsalb3rt** [ta-vivo/ta-vivo-landing#79]
This dependency need a human touch, why ? This has a breaking changes in the GRID system.

The next image have a red arrow, this content need to move to the green square.

![image](https://user-images.githubusercontent.com/35310226/171972345-da66b0ab-0280-451b-8544-854f17495f9f.png)

**How to make a upgrade**

- In local environment install this project
- Run `yarn upgrade-interactive` and search for @mui/material
- Got to the official documentation and compare the GRID system in the documentation with the structure are in the project

Extra note: If you can test the complete project, I being thankful.

Thanks ❤️

**Comment by itsalb3rt** [comment]
@rafieltq maybe you can do it ? 😃

**Comment by itsalb3rt** [comment]
Move to @Jadhielv maybe you can do it ? 😄

**Comment by Jadhielv** [comment]
@itsalb3rt yep, I'll do that.
